name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.3
          - 27.2
          - 28.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - uses: cask/setup-cask@v1.1
    - name: Install packages from Cask file
      run: cask
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: 2.6
    - name: Run tests
      run: make ci-test
